name = "BrauerGroup"
keywords = ["math", "algebra", "ring-theory", "algebraic-number-theory"]
defaultTargets = ["BrauerGroup"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.24.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "BrauerGroup"
